baseURL = "http://example.org/"
languageCode = "en-us"
title = "youngjin's site"
theme = "hugo-yj-theme"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "site of a student, hobbyist programmer, and tech geek"
  avatar = "img/avatar_512.jpg"
  favicon = "img/avatar_512.jpg"
  portfolio = [
    { Name = 'Elements & Principles of Design', Image = 'img/elem.png',  },
    { Name = 'Digital Illustration', Image = 'img/digitalillustration.png',  },
    { Name = 'Movie Poster', Image = 'img/movieposter.png',  },
    { Name = 'Propaganda Poster', Image = 'img/propagandaposter.png',  },
    { Name = 'Monogram', Image = 'img/monogram.png',  },
    { Name = 'Cityguide', Image = 'img/cityguide.png',  },
    { Name = 'Flyer', Image = 'img/youngjin_flyer.jpg',  },
    { Name = 'Memory Project', Image = 'img/memory.png',  },
    { Name = 'Rotoscope Animation', Image = 'img/animation.gif' }]

[permalinks]
  posts = "/:year/:title/"

[menu]
  [[menu.navigation]]
    name = 'Github'
    url = 'https://github.com/youngjinpark20'
  [[menu.navigation]]
    name = 'Baekjoon'
    url = 'https://www.acmicpc.net/user/youngjinp20'
  [[menu.navigation]]
    name = 'Portfolio'
    url = 'portfolio'
