baseURL = "https://youngjin.io/"
languageCode = "en-us"
title = "youngjin's site"
theme = "hugo-yj-theme"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
	description = "site of a student, hobby programmer, and tech geek"
	avatar = "img/avatar_512.jpg"
	favicon = "img/avatar_512.jpg"

[permalinks]
	posts = "/:year/:title/"

[menu]
	[[menu.navigation]]
		name = 'Github'
		url = 'https://github.com/yjp20'
		weight = 3
	[[menu.navigation]]
		name = 'Codeforces'
		url = 'https://codeforces.com/profile/youngjinp20'
		weight = 4
	[[menu.navigation]]
		name = 'Portfolio'
		url = 'portfolio'
		weight = 1
	[[menu.navigation]]
		name = 'Posts'
		url = 'posts'
		weight = -1
	[[menu.navigation]]
		name = 'Projects'
		url = 'projects'
		weight = 2
